/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MasterplanRouteImport } from './routes/masterplan'
import { Route as LazerRouteImport } from './routes/lazer'
import { Route as InfraestruturaRouteImport } from './routes/infraestrutura'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EmpreendimentoRouteImport } from './routes/empreendimento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPreviewPageRouteImport } from './routes/admin.preview.$page'

const MasterplanRoute = MasterplanRouteImport.update({
  id: '/masterplan',
  path: '/masterplan',
  getParentRoute: () => rootRouteImport,
} as any)
const LazerRoute = LazerRouteImport.update({
  id: '/lazer',
  path: '/lazer',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraestruturaRoute = InfraestruturaRouteImport.update({
  id: '/infraestrutura',
  path: '/infraestrutura',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpreendimentoRoute = EmpreendimentoRouteImport.update({
  id: '/empreendimento',
  path: '/empreendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewPageRoute = AdminPreviewPageRouteImport.update({
  id: '/admin/preview/$page',
  path: '/admin/preview/$page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empreendimento': typeof EmpreendimentoRoute
  '/galeria': typeof GaleriaRoute
  '/infraestrutura': typeof InfraestruturaRoute
  '/lazer': typeof LazerRoute
  '/masterplan': typeof MasterplanRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/preview/$page': typeof AdminPreviewPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empreendimento': typeof EmpreendimentoRoute
  '/galeria': typeof GaleriaRoute
  '/infraestrutura': typeof InfraestruturaRoute
  '/lazer': typeof LazerRoute
  '/masterplan': typeof MasterplanRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/preview/$page': typeof AdminPreviewPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empreendimento': typeof EmpreendimentoRoute
  '/galeria': typeof GaleriaRoute
  '/infraestrutura': typeof InfraestruturaRoute
  '/lazer': typeof LazerRoute
  '/masterplan': typeof MasterplanRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/preview/$page': typeof AdminPreviewPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/empreendimento'
    | '/galeria'
    | '/infraestrutura'
    | '/lazer'
    | '/masterplan'
    | '/admin/login'
    | '/admin/'
    | '/admin/preview/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/empreendimento'
    | '/galeria'
    | '/infraestrutura'
    | '/lazer'
    | '/masterplan'
    | '/admin/login'
    | '/admin'
    | '/admin/preview/$page'
  id:
    | '__root__'
    | '/'
    | '/empreendimento'
    | '/galeria'
    | '/infraestrutura'
    | '/lazer'
    | '/masterplan'
    | '/admin/login'
    | '/admin/'
    | '/admin/preview/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpreendimentoRoute: typeof EmpreendimentoRoute
  GaleriaRoute: typeof GaleriaRoute
  InfraestruturaRoute: typeof InfraestruturaRoute
  LazerRoute: typeof LazerRoute
  MasterplanRoute: typeof MasterplanRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPreviewPageRoute: typeof AdminPreviewPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/masterplan': {
      id: '/masterplan'
      path: '/masterplan'
      fullPath: '/masterplan'
      preLoaderRoute: typeof MasterplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lazer': {
      id: '/lazer'
      path: '/lazer'
      fullPath: '/lazer'
      preLoaderRoute: typeof LazerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infraestrutura': {
      id: '/infraestrutura'
      path: '/infraestrutura'
      fullPath: '/infraestrutura'
      preLoaderRoute: typeof InfraestruturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimento': {
      id: '/empreendimento'
      path: '/empreendimento'
      fullPath: '/empreendimento'
      preLoaderRoute: typeof EmpreendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/preview/$page': {
      id: '/admin/preview/$page'
      path: '/admin/preview/$page'
      fullPath: '/admin/preview/$page'
      preLoaderRoute: typeof AdminPreviewPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpreendimentoRoute: EmpreendimentoRoute,
  GaleriaRoute: GaleriaRoute,
  InfraestruturaRoute: InfraestruturaRoute,
  LazerRoute: LazerRoute,
  MasterplanRoute: MasterplanRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPreviewPageRoute: AdminPreviewPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
